# 开发环境 和 测试环境 都使用这个配置
server:
  port: 8087
  # session失效时间
  servlet:
    context-path: /unity_up
    session:
      timeout: 7200s
      cookie:
        name: unity_up-session

spring:
  application:
    name: prod_unity_up
  profiles:
    include: sysconfig
  #json数据格式化
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.26:3306/unity_up_prod?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
#    url: jdbc:mysql://192.168.0.144:3306/unity_up?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: xuejinyu

    # Druid连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化
      initialSize: 3
      # 最大
      maxActive: 20
      # 最小
      minIdle: 3
      # 最大连接等待超时时间
      maxWait: 60000
      # 打开PSCache,并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间,单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 设置连接在池中最大存活时长，超过上限才会被清理
      maxEvictableIdleTimeMillis: 600000
      # 配置监控统计拦截的filters,去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat, wall, slf4j

  # http
  http:
    # 过滤字符编码
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  # 文件上传大小
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 2048MB
      # 一次传多个文件的总大小
      max-request-size: 2048MB

  # 取消spring对freemarker默认templates目录的检测
  freemarker:
    check-template-location: false
  jpa:
    open-in-view: false

# OBS 配置
cdn:
  accessKey: EV6YS2YONZHD3I8EB8NL
  secretKey: oJ2R07XKzqyOvF75ArURCf35MatchBi6miXF1p5D
  endPoint: https://obs.cn-east-2.myhuaweicloud.com
  # CDN 配置
  bucket: h5gcdn
#  bucket: hcg62file
  # cdn的server
  server: https://h5gcdn.hippotap.cn/
#  server: https://hcg62cdn.libii.cn/

test:
  # 测试服资源访问地址
  url: http://192.168.0.21/
  # 资源包存放路径
  path: /home/webgl_data/

# 前端整合页面地址
auth-platforms: http://192.168.0.23:28012/#/platforms
# sso项目地址
auth-sso: http://localhost:9999/permission

# keycloak配置
keycloak:
  realm: ly-test-gateway
  auth-server-url: http://192.168.0.20:8080/auth
  resource: unity_up
  ssl-required: none
  public-client: true
  autodetect-bearer-only: true
  always-refresh-token: true

# Eureka配置
eureka:
  instance:
    prefer-ip-address: true
    #    instance-id: 127.0.0.1
    instance-id: 192.168.0.21
  client:
    serviceUrl:
      defaultZone: http://libii:123456@192.168.0.23:8134/eureka/

# Eureka 远程调用前缀
rpc:
  prefix:
    sso: http://PERMISSION/permission

# 定时任务周期
timed-task:
  white-list-refresh-cycle: 50000
  hot-update-refresh-cycle: 50000

s3-server-url: https://d1zj49tg1cr53u.cloudfront.net/
#192.168.5.201