# SSO-Client 配置信息
security:
  oauth2:
    client:
      client-id: unity_up
      client-secret: 123456
      user-authorization-uri: ${auth-server}/oauth/authorize
      access-token-uri: ${auth-server}/oauth/token
    resource:
      jwt:
        key-uri: ${auth-server}/oauth/token_key
      userInfoUri: ${auth-server}/user/sso

# Druid 连接池需要为不同war包指定不同的实例化名称
spring:
  jmx:
    default-domain: unity_up
###   Mybatis Config  ###
mybatis:
  check-config-location: true
  typeAliasesPackage: com.libii.sso.**.domain
  mapperLocations: classpath:mapper/**/*.xml
  type-handlers-package: com.libii.sso.common.mybatis.handler.*

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

###   通用 Mapper  ###
mapper:
  IDENTITY: mysql
  notEmpty: false
  mappers:
    - com.libii.sso.common.core.Mapper
    - com.libii.sso.common.core.TkMapper

# 日志
logging.config: classpath:logging-spring.xml
swagger:
  title: 后台单点登录客户端模板系统
  basepackage: com.libii.sso
  version: 1.0.0
  contract-name: lirong
  contract-url: https://blog.csdn.net/qq_34997906
  contract-email: lirong@libii.com

client:
  # 跨域ip处理
  origins:
    - http://localhost:8090
    - http://localhost:8080
    - http://localhost:9999
    - http://192.168.1.201:9999

  # 系统模块ID  新克隆的项目，一定记得更改此处
  moduleId: 2

